import { Router } from 'express';
import sessionsRoutes from './sessions.routes';
import adminsRoutes from './admins.routes';
import treinadoresRoutes from './treinadores.routes';
import clientesRoutes from './clientes.routes';
import trainingsRoutes from './trainings.routes';
import clientTrainingRoutes from './clientTraining.routes';
import clienteEstatisticRoutes from './clienteEstatistic.routes';
import agendaPointRoutes from './agendaPoint.routes';
import exercisesRoutes from './exercises.routes';
import exerciseTrainingsRoutes from './exerciseTrainings.routes';
import clientePhotosRoutes from './clientePhotos.routes';
import treinadorPhotosRoutes from './treinadorPhotos.routes';
import studentProfilePhotoRoutes from './studentProfilePhoto.routes';
import trainerProfilePhotoRoutes from './trainerProfilePhoto.routes';
import feedbackRoutes from './feedback.routes';
import feedbackPhotosRoutes from './feedbackPhotos.routes';
import repetitionsRoutes from './repetitions.routes';
import trainingRoutinesRoutes from './trainingRoutines.routes';
import routineTrainingsRoutes from './routineTrainings.routes';
import routineProgressRoutes from './routineProgress.routes';
import notificationsRoutes from './notifications.routes';
import trainerSchedulesRoutes from './trainerSchedules.routes';
import timelineRoutes from './timeline.routes';

const routes = Router();

routes.use("/sessions", sessionsRoutes);
routes.use("/admins", adminsRoutes);
routes.use("/trainers", treinadoresRoutes);
routes.use("/trainers", trainerSchedulesRoutes);
routes.use("/students", clientesRoutes);
routes.use("/trainings", trainingsRoutes);
routes.use("/client-trainings", clientTrainingRoutes);
routes.use("/student-statistics", clienteEstatisticRoutes);
routes.use("/schedule-appointments", agendaPointRoutes);
routes.use("/exercises", exercisesRoutes);
routes.use("/exercise-trainings", exerciseTrainingsRoutes);
routes.use("/students", clientePhotosRoutes);
routes.use("/trainers", treinadorPhotosRoutes);
routes.use("/students", studentProfilePhotoRoutes);
routes.use("/trainers", trainerProfilePhotoRoutes);
routes.use("/feedback", feedbackRoutes);
routes.use("/feedback", feedbackPhotosRoutes);
routes.use("/notifications", notificationsRoutes);
routes.use("/repetitions", repetitionsRoutes);
routes.use("/training-routines", trainingRoutinesRoutes);
routes.use("/routine-trainings", routineTrainingsRoutes);
routes.use("/routine-progress", routineProgressRoutes);
routes.use("/timeline", timelineRoutes);

export default routes;
